package fr.epsi.mspr.agents;

import java.util.List;
import java.util.StringJoiner;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;

class AgentsIndexCreator {
    private List<Agent> agents;

    public AgentsIndexCreator(List<Agent> agents,String outDir) {
        this.agents = agents;
    }

    public String generateIndex() {
        StringJoiner html = new StringJoiner("\n");
        html.add("<!DOCTYPE html\">");
        html.add("<html lang=\"fr\">");
        html.add("<head>");
        html.add("    <meta charset=\"utf-8\" />");
        html.add("    <title>GO Securi</title>");
        html.add("<style type=\"text/css\">html pre{width: 636px ;}</style>");
        html.add("    <style type=\"text/css\">");
        html.add("        body {");
        html.add("            margin: 10px 0;");
        html.add("            padding: 0;");
        html.add("            text-align: center;");
        html.add("            font: 0.8em \"Trebuchet MS\", helvetica, sans-serif;");
        html.add("            background: rgb(213, 216, 204);");
        html.add("        }");
        html.add("        ");
        html.add("        div#conteneur {");
        html.add("            width: 1200px;");
        html.add("            height: 1000px;");
        html.add("            margin: 0 auto;");
        html.add("            text-align: left;");
        html.add("            border: 2px solid rgb(0, 0, 0);");
        html.add("            background: #fff;");
        html.add("        }");
        html.add("        ");
        html.add("        h1#header {");
        html.add("            height: 258px;");
        html.add("            margin: 0;");
        html.add("            background: url(logo.png) no-repeat left top;");
        html.add("        }");
        html.add("        ");
        html.add("        h1#header a {");
        html.add("            width: 400px;");
        html.add("            height: 120px;");
        html.add("            display: block;");
        html.add("            background: url(title.png) no-repeat;");
        html.add("            position: relative;");
        html.add("            left: 350px;");
        html.add("            top: 15px;");
        html.add("            text-indent: -5000px;");
        html.add("            margin-left: 120px;");
        html.add("        }");
        html.add("        ");
        html.add("        ul#menu {");
        html.add("            height: 35px;");
        html.add("            margin: 0;");
        html.add("            padding: 0;");
        html.add("            background: url(bg_menu.gif) repeat-x 0 -25px;");
        html.add("            list-style-type: none;");
        html.add("        }");
        html.add("        ");
        html.add("        ul#menu li {");
        html.add("            float: left;");
        html.add("            text-align: center;");
        html.add("        }");
        html.add("        ");
        html.add("        ul#menu li a {");
        html.add("            width: 130px;");
        html.add("            line-height: 25px;");
        html.add("            font-size: 1.2em;");
        html.add("            font-weight: bold;");
        html.add("            letter-spacing: 2px;");
        html.add("            color: #fff;");
        html.add("            display: block;");
        html.add("            text-decoration: none;");
        html.add("            border-right: 2px solid #dea;");
        html.add("        }");
        html.add("        ");
        html.add("        ul#menu li a:hover {");
        html.add("            background: url(bg_menu.gif) repeat-x 0 0;");
        html.add("        }");
        html.add("        ");
        html.add("        div#contenu {");
        html.add("            padding: 0 25px 0 100px;");
        html.add("        }");
        html.add("        ");
        html.add("        div#contenu h2 {");
        html.add("            padding-left: 25px;");
        html.add("            line-height: 25px;");
        html.add("            font-size: 1.4em;");
        html.add("            background: url(mini.png) no-repeat left bottom;");
        html.add("            color: rgb(34, 82, 187);");
        html.add("            border-bottom: 1px solid rgb(#379EC1);");
        html.add("        }");
        html.add("        ");
        html.add("        div#contenu h3 {");
        html.add("            margin-left: 15px;");
        html.add("            padding-left: 5px;");
        html.add("            border-bottom: 1px solid #9b2;");
        html.add("            border-left: 3px solid #9b2;");
        html.add("            color: #9b2;");
        html.add("        }");
        html.add("        ");
        html.add("        div#contenu p {");
        html.add("            text-align: justify;");
        html.add("            text-indent: 2em;");
        html.add("            line-height: 1.7em;");
        html.add("        }");
        html.add("        ");
        html.add("        div#contenu a {");
        html.add("            color: #8a0;");
        html.add("        }");
        html.add("        ");
        html.add("        div#contenu a:hover {");
        html.add("            color: #9b2;");
        html.add("        }");
        html.add("        ");
        html.add("        p#footer {");
        html.add("            margin: 0;");
        html.add("            padding-right: 10px;");
        html.add("            line-height: 30px;");
        html.add("            text-align: right;");
        html.add("            color: #8a0;");
        html.add("        }");
        html.add("        ");
        html.add("        pre {");
        html.add("            overflow: auto;");
        html.add("            background: #dea;");
        html.add("            border: 2px solid #9b2;");
        html.add("            padding: 5px 0 0 5px;");
        html.add("            font-size: 1.2em;");
        html.add("        }");
        html.add("        ");
        html.add("        * html pre {");
        html.add("            width: 636px;");
        html.add("        }");
        html.add("        ");
        html.add("        pre span {");
        html.add("            color: #560;");
        html.add("        }");
        html.add("        ");
        html.add("        pre span.comment {");
        html.add("            color: #b30000;");
        html.add("        }");
        html.add("    </style>");
        html.add("</head>");
        html.add("<body>");
        html.add("    <div id=\"conteneur\">");
        html.add("        <h1 id=\"header\"><a href=\"#\" title=\"GO Securi - Accueil\"><span>GO Securi</span></a></h1>");
        html.add("        <nav>");
        html.add("            <ul id=\"menu\">");
        html.add("                <li><a href=\"#\">Liste Agents</a></li>");
        html.add("            </ul>");
        html.add("        </nav>");
        html.add("        <div id=\"contenu\">");
        html.add("            <h2>Liste des agents :</h2>");
        html.add("            <nav>");
        html.add("                <ul id=\"liste-agents\">");
        for (Agent agent : agents) {
            html.add("                    <li><a href=\"./"+agent.getFileName()+"/index.html\" >"+agent.getFullName()+"</a></li>");
        }
        html.add("                </ul>");
        html.add("            </nav>");
        html.add("        </div>");
        html.add("        <p id=\"footer\"><a href=\"#header\">Haut de la page</a></p>");
        html.add("    </div>");
        html.add("</body>");
        html.add("</html>");
        return html.toString();
    }

    public String generateIndexJSON() {
        JsonObject jOb = new JsonObject();
        JsonArray jAr = new JsonArray();
        for (Agent agent : agents) {
            JsonObject jAgent = new JsonObject();
            jAgent.addProperty("fullname", agent.getFullName());
            jAgent.addProperty("agentUrl", "./"+agent.getFileName()+"/"+agent.getFileName()+".json");
            jAr.add(jAgent);
        }
        jOb.add("agents", jAr);
        return jOb.toString();
    }
}